dist: xenial

language: go

sudo: required

go:
  - 1.15

services:
  - docker

before_install:
  - wget https://github.com/aquasecurity/trivy/releases/download/v0.15.0/trivy_0.15.0_Linux-64bit.tar.gz
  - sudo tar -C /usr/local/bin -zxf trivy_0.15.0_Linux-64bit.tar.gz
  - curl --silent --show-error --location --output /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.8.1/kind-linux-amd64  # 1.12 nodes not supported after this version
  - chmod +x /usr/local/bin/kind /usr/local/bin/trivy

install:
  - make kind setup

script:
  - make build integrated-test
