name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=https://github.com/nixos/nixpkgs/archive/9c8ff8b426a8b07b9e0a131ac3218740dc85ba1e.tar.gz
#
#      - name: Kind setup
#        id: kind
#        run: nix-shell --command "make kind setup"
#
#      - name: Run integration tests
#        id: integrated-test
#        run: nix-shell --command "make build integrated-test"
#
#      - name: Publish Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: success() || failure()
#        with:
#          files: |
#            test-reports/*-tests-report.xml

  dist:
    needs: [build]
    name: Build executables for other platforms
    strategy:
      matrix:
        os: [windows, linux]
        arch: [amd64, 386]
        include:
          - os: darwin
            arch: amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=https://github.com/nixos/nixpkgs/archive/9c8ff8b426a8b07b9e0a131ac3218740dc85ba1e.tar.gz

      - name: Build executable for ${{matrix.os}} on ${{matrix.arch}}
        run: nix-shell --command "make dist"
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Store dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/bin/production-readiness*
          retention-days: 1

  release:
    #if: github.ref == 'refs/heads/main' && success()
    if: success()
    uses: ./.github/workflows/release.yaml
    needs: [dist]
    name: Release
    with:
      dry-run: false
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
