name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=https://github.com/nixos/nixpkgs/archive/9c8ff8b426a8b07b9e0a131ac3218740dc85ba1e.tar.gz

      - name: Kind setup
        id: kind
        run: nix-shell --command "make kind setup"

      - name: Run integration tests
        id: integrated-test
        run: nix-shell --command "make build integrated-test"

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          path: "*-tests-report.xml"
          reporter: java-junit
